# Generated by Django 5.0.1 on 2024-11-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleoauthkeys',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
